### ISSUE TITLE
timeline in timing correct?

### ISSUE THREAD

**Issue by bergerrjf** [hoehleatsu/mt3002-summer2020#2]
In lecture L03 (1/2) at about 11:46 I wonder if the timelines for "symptom period" and "infection period" are correct, or I possibly misunderstand them. But I thought they should start at at "onset of symptoms" and "infectious"?

**Comment by mhoehle** [comment]
Thanks for pointing this out.! You are right, Tom posted this as an errata back in the course. Have added this as errata information to the video description on both the youtube and video.su.se upload. Thanks again.
